;;;; machine.lisp — machine state + instruction interpreter (spec §4, §6)
(in-package #:secd-emulator.vm)

;;; Opcodes (bytecode.h)
(defconstant +op-stop+ #x00) (defconstant +op-ldm+ #x01)
(defconstant +op-ldc+ #x02)  (defconstant +op-ldf+ #x03)
(defconstant +op-lde+ #x04)  (defconstant +op-ldcw+ #x05)
(defconstant +op-add+ #x10)  (defconstant +op-sub+ #x11)
(defconstant +op-mul+ #x12)  (defconstant +op-div+ #x13)
(defconstant +op-mod+ #x14)  (defconstant +op-neg+ #x15)
(defconstant +op-eq+ #x20)   (defconstant +op-lt+ #x21)
(defconstant +op-gt+ #x22)   (defconstant +op-le+ #x23)
(defconstant +op-ge+ #x24)   (defconstant +op-not+ #x25)
(defconstant +op-car+ #x30)  (defconstant +op-cdr+ #x31)
(defconstant +op-cons+ #x32) (defconstant +op-ldv+ #x33)
(defconstant +op-vref+ #x34) (defconstant +op-vstor+ #x35)
(defconstant +op-mkv+ #x36)  (defconstant +op-len+ #x37)
(defconstant +op-ld+ #x40)   (defconstant +op-st+ #x41)
(defconstant +op-args+ #x42) (defconstant +op-ldg+ #x43)
(defconstant +op-stg+ #x44)  (defconstant +op-sel+ #x50)
(defconstant +op-join+ #x51) (defconstant +op-loop+ #x52)
(defconstant +op-brk+ #x53)  (defconstant +op-jmp+ #x54)
(defconstant +op-app+ #x60)  (defconstant +op-rtn+ #x61)
(defconstant +op-call+ #x62) (defconstant +op-prim+ #x70)
(defconstant +op-prn+ #x78)  (defconstant +op-dump+ #x79)
(defconstant +op-gc+ #x7A)   (defconstant +op-nop+ #x7B)
(defconstant +op-pop+ #x7C)  (defconstant +op-error+ #xFF)

(defconstant +err-none+ 0)          (defconstant +err-stack-overflow+ 1)
(defconstant +err-stack-underflow+ 2)(defconstant +err-heap-full+ 3)
(defconstant +err-invalid-handle+ 4)(defconstant +err-type-error+ 5)
(defconstant +err-div-zero+ 6)      (defconstant +err-undef-symbol+ 7)
(defconstant +err-prim-not-found+ 8)

(defvar *registry* nil
  "Bound during execution: hash primitive-id -> (heap args) => handle.")

(defstruct (machine (:constructor %make-machine))
  heap
  (code nil :type (or null (simple-array (unsigned-byte 8) (*))))
  (code-start 0 :type (integer 0 #xFFFFFFFF))
  (code-len 0 :type (integer 0 #xFFFFFFFF))
  (ip 0 :type (integer 0 #xFFFFFFFF))
  ;; value stack
  (stack (make-array 1024 :element-type 'handle)) (sp 0)
  (e +nil+) (g +nil+)
  (dump nil)                                   ; alist of (e . ret)
  (error-code 0) (running nil) (steps 0) (max-steps 0)
  (pool-loaded nil)
  ;; host integration
  (console-out-hook nil)                       ; fn (string)
  (hal-event-hook nil)                         ; fn (keyword plist)
  (console-in (make-array 64 :element-type '(unsigned-byte 8)
                             :adjustable t :fill-pointer 0)))

(defun make-machine (heap) (%make-machine :heap heap))

(defun machine-console-in-push (m byte)
  (vector-push-extend byte (machine-console-in m) 256))

(defun emit-out (m string)
  (when (machine-console-out-hook m)
    (funcall (machine-console-out-hook m) string)))

(defun emit-event (m kind &rest plist)
  (when (machine-hal-event-hook m)
    (funcall (machine-hal-event-hook m) kind plist)))

(declaim (inline vm-push vm-pop))
(defun vm-push (m v)
  (with-slots (stack sp) m
    (if (>= sp (length stack))
        (progn (setf (machine-error-code m) +err-stack-overflow+) nil)
        (progn (setf (aref stack sp) v) (incf sp) t))))
(defun vm-pop (m)
  (with-slots (stack sp) m
    (if (zerop sp)
        (progn (setf (machine-error-code m) +err-stack-underflow+) +nil+)
        (decf sp))
    (aref stack sp)))

(declaim (inline rd-u8 rd-u16))
(defun rd-u8 (buf i) (aref buf i))
(defun rd-u16 (buf i) (logior (ash (aref buf i) 8) (aref buf (1+ i))))

;;; ---- environment / globals helpers -------------------------------------
(defun env-ref (m index)
  (loop for cur = (machine-e m) then (heap-cdr (machine-heap m) (handle-index cur))
        for i from 0
        do (when (/= (handle-tag cur) +tag-pair+) (return +nil+))
        when (= i index) return (heap-car (machine-heap m) (handle-index cur))))

(defun (setf env-ref) (val m index)
  (let ((cur (machine-e m)))
    (loop for i from 0 below index
          do (when (/= (handle-tag cur) +tag-pair+) (return))
             (setf cur (heap-cdr (machine-heap m) (handle-index cur))))
    (when (= (handle-tag cur) +tag-pair+)
      (set-heap-car (machine-heap m) (handle-index cur) val)
      val)))

(defun global-ref (m index)
  (loop for cur = (machine-g m) then (heap-cdr (machine-heap m) (handle-index cur))
        for i from 0
        do (when (/= (handle-tag cur) +tag-pair+) (return +nil+))
        when (= i index) return (heap-car (machine-heap m) (handle-index cur))))

(defun (setf global-ref) (val m index)
  (with-slots (heap g) m
    ;; collect existing cells
    (let ((cells '()) (cur g))
      (loop while (= (handle-tag cur) +tag-pair+)
            do (push cur cells)
               (setf cur (heap-cdr heap (handle-index cur))))
      ;; extend with fresh cells until we have index+1
      (loop for k from (length cells) to index
            do (let ((cell (cons-values heap +nil+ +nil+)))
                 (cond ((null cells) (setf g cell))
                       (t (set-heap-cdr heap (handle-index (first cells)) cell)))
                 (push cell cells)))
      (set-heap-car heap (handle-index (first cells)) val)
      val)))

;;; ---- loader -------------------------------------------------------------
(defun find-secd-magic (buf)
  (or (and (>= (length buf) 4)
           (char= (code-char (aref buf 0)) #\S) (char= (code-char (aref buf 1)) #\E)
           (char= (code-char (aref buf 2)) #\C) (char= (code-char (aref buf 3)) #\D)
           0)
      (loop for i from 0 to (- (length buf) 4)
            when (and (= (aref buf (+ i 0)) 83) (= (aref buf (+ i 1)) 69)
                      (= (aref buf (+ i 2)) 67) (= (aref buf (+ i 3)) 68))
              return i)))

"Load a .secd unit (or firmware image containing one). Returns :ok or keyword."
(defun load-bytecode (m buf)
  (let ((pos (find-secd-magic buf)))
    (unless pos (return-from load-bytecode :no-bytecode))
    (let* ((cs (logior (ash (aref buf (+ pos 8)) 8) (aref buf (+ pos 9))))
           (cn (logior (ash (aref buf (+ pos 10)) 8) (aref buf (+ pos 11))))
           (start (+ pos 14))
           (len (+ cs cn)))
      ;; Execute a COPY of just the code unit: all operand addresses inside
      ;; are relative to it (the C runtime passes ptr+14 as well).
      (setf (machine-code m) (subseq buf start (+ start len))
            (machine-code-start m) 0
            (machine-code-len m) len
            (machine-ip m) 0
            (machine-error-code m) 0
            (machine-steps m) 0
            (machine-running m) t)
      (reset-machine m :reload t)
      ;; ROM pool registration (trailer magic 0xB1C5 at end of unit)
      (let* ((end (+ start len))
             (magic (logior (ash (aref buf (- end 2)) 8) (aref buf (- end 1)))))
        (when (= magic #xB1C5)
          (let* ((psize (logior (ash (aref buf (- end 4)) 8) (aref buf (- end 3))))
                 (pstart (- end 4 psize))
                 (count (logior (ash (aref buf pstart) 8) (aref buf (1+ pstart)))))
            (dotimes (i count)
              (let* ((dir (+ pstart 2 (* 4 i)))
                     (off (logior (ash (aref buf dir) 8) (aref buf (1+ dir))))
                     (l   (logior (ash (aref buf (+ dir 2)) 8) (aref buf (+ dir 3)))))
                (bv-register-rom (machine-heap m) buf
                                 (+ pstart 2 (* 4 count) off) l))))
          (setf (machine-pool-loaded m) t)))
      :ok)))

"Reset registers; keeps loaded code + pool registrations unless :reload."
(defun reset-machine (m &key reload)
  (declare (ignore reload))
  (with-slots (ip e g dump error-code steps running sp code-start) m
    (setf ip code-start e +nil+ g +nil+ dump nil
          error-code 0 steps 0 running t sp 0)))

(defun push-dump-frame (m e ret)
  (push (cons e ret) (machine-dump m)))

;;; ---- interpreter --------------------------------------------------------
;; forward decl from primitives
(defun call-prim-by-name (name heap args)
  "Fallback used before a registry exists.")

(defun exec-one (m)
  (with-slots (code code-start ip sp e g dump error-code heap) m
    (labels ((off (n) (+ code-start ip n))
             (u16-at (n) (rd-u16 code (off n)))
             (fail (c) (setf error-code c)))
      (let ((op (aref code (off 0))))
        (macrolet ((pushv (v) `(unless (vm-push m ,v) (fail +err-stack-overflow+)))
                   (binop (fn) `(let ((b (vm-pop m)) (a (vm-pop m)))
                                  (pushv (,fn (machine-heap m)
                                              (cons-values (machine-heap m) a
                                                           (cons-values (machine-heap m) b +nil+)))))))
          (case op
            (#.+op-stop+ (setf (machine-running m) nil))
            (#.+op-nop+ (incf ip 1))
            (#.+op-pop+ (vm-pop m) (incf ip 1))
            (#.+op-ldm+ (let ((addr (u16-at 1))) (pushv (heap-car heap addr))) (incf ip 3))
            (#.+op-ldc+ (let ((raw (u16-at 1)))
                          (pushv (mk-handle +tag-fixnum+ (logand raw #x0FFF))))
                        (incf ip 3))
            (#.+op-ldcw+ (let ((v24 (logior (ash (rd-u8 code (off 1)) 16)
                                            (ash (rd-u8 code (off 2)) 8)
                                            (rd-u8 code (off 3)))))
                           (let ((slot (bv-alloc heap (if (zerop v24) 1
                                                          (ceiling (integer-length v24) 8)))))
                             (if (null slot)
                                 (fail +err-heap-full+)
                                 (progn
                                   (let ((n (if (zerop v24) 1 (ceiling (integer-length v24) 8))))
                                     (dotimes (k n) (bv-write heap slot k (ldb (byte 8 (* 8 k)) v24))))
                                   (let ((oi (heap-alloc heap +tag-bignum+)))
                                     (if (zerop oi)
                                         (fail +err-heap-full+)
                                         (progn (set-heap-car heap oi 0)
                                                (set-heap-cdr heap oi slot)
                                                (pushv (mk-handle +tag-bignum+ oi)))))
                                   (incf ip 4))))))
            (#.+op-ldf+ (let ((cl (cons-values heap (mk-fixnum (u16-at 1)) e)))
                          (pushv cl) (incf ip 3)))
            (#.+op-lde+ (pushv e) (incf ip 1))
            (#.+op-ldv+ (pushv (mk-handle +tag-bytevec+ (u16-at 1))) (incf ip 3))
            (#.+op-args+ (let ((n (rd-u8 code (off 1))))
                           (dotimes (k n)
                             (setf e (cons-values heap (vm-pop m) e)))
                           (incf ip 2)))
            (#.+op-ld+ (pushv (env-ref m (u16-at 1))) (incf ip 3))
            (#.+op-st+ (let ((v (vm-pop m))) (setf (env-ref m (u16-at 1)) v) (pushv v)) (incf ip 3))
            (#.+op-ldg+ (pushv (global-ref m (u16-at 1))) (incf ip 3))
            (#.+op-stg+ (let ((v (vm-pop m))) (setf (global-ref m (u16-at 1)) v) (pushv v)) (incf ip 3))
            ((#.+op-add+ #.+op-sub+ #.+op-mul+ #.+op-div+ #.+op-mod+
              #.+op-eq+ #.+op-lt+ #.+op-gt+)
             (let* ((*current-machine* m)
                    (b (vm-pop m)) (a (vm-pop m))
                    (args (cons-values heap a (cons-values heap b +nil+)))
                    (res (call-core-op op heap args)))
               (pushv res) (incf ip 1)))
            (#.+op-le+ (bin-le m) (incf ip 1))
            (#.+op-ge+ (bin-ge m) (incf ip 1))
            (#.+op-not+ (let ((a (vm-pop m))) (pushv (mk-bool (not (truthy a))))) (incf ip 1))
            (#.+op-neg+ (let ((a (vm-pop m))) (pushv (mk-fixnum (- (fixnum-value a))))) (incf ip 1))
            (#.+op-car+ (let ((p (vm-pop m)))
                          (pushv (if (= (handle-tag p) +tag-pair+)
                                     (heap-car heap (handle-index p)) +nil+)))
                        (incf ip 1))
            (#.+op-cdr+ (let ((p (vm-pop m)))
                          (pushv (if (= (handle-tag p) +tag-pair+)
                                     (heap-cdr heap (handle-index p)) +nil+)))
                        (incf ip 1))
            (#.+op-cons+ (let ((d (vm-pop m)) (a (vm-pop m))) (pushv (cons-values heap a d)))
                         (incf ip 1))
            (#.+op-vref+ (let ((idx (vm-pop m)) (vec (vm-pop m)))
                           (if (and (= (handle-tag vec) +tag-bytevec+)
                                    (= (handle-tag idx) +tag-fixnum+))
                               (let ((b (bv-read heap (handle-index vec) (fixnum-value idx))))
                                 (if (< b 0) (fail +err-invalid-handle+) (pushv (mk-fixnum b))))
                               (fail +err-type-error+)))
                         (incf ip 1))
            (#.+op-vstor+ (let ((val (vm-pop m)) (idx (vm-pop m)) (vec (vm-pop m)))
                            (if (and (= (handle-tag vec) +tag-bytevec+)
                                     (= (handle-tag idx) +tag-fixnum+)
                                     (= (handle-tag val) +tag-fixnum+))
                                (if (not (bv-write heap (handle-index vec)
                                                   (fixnum-value idx)
                                                   (handle-index val)))
                                    (fail +err-invalid-handle+)
                                    (pushv val))
                                (fail +err-type-error+)))
                          (incf ip 1))
            (#.+op-mkv+ (let ((n (vm-pop m)))
                          (if (/= (handle-tag n) +tag-fixnum+)
                              (fail +err-type-error+)
                              (let ((slot (bv-alloc heap (fixnum-value n))))
                                (if (null slot) (fail +err-heap-full+) (pushv (mk-handle +tag-bytevec+ slot))))))
                        (incf ip 1))
            (#.+op-len+ (let ((v (vm-pop m)))
                          (pushv
                           (cond ((= (handle-tag v) +tag-bytevec+)
                                  (mk-fixnum (bv-len heap (handle-index v))))
                                 ((= (handle-tag v) +tag-pair+)
                                  (let ((n 0) (cur v))
                                    (loop while (= (handle-tag cur) +tag-pair+)
                                          do (incf n)
                                             (setf cur (heap-cdr heap (handle-index cur))))
                                    (mk-fixnum n)))
                                 (t (mk-fixnum 0)))))
                        (incf ip 1))
            (#.+op-sel+ (let ((cond-v (vm-pop m)) (else (u16-at 1)))
                          (if (truthy cond-v) (incf ip 3) (setf ip else))))
            (#.+op-join+ (let ((frame (pop dump))) (setf ip (cdr frame))))
            (#.+op-loop+ (setf ip (u16-at 1)))
            (#.+op-jmp+ (setf ip (u16-at 1)))
            (#.+op-brk+ (emit-event m :break nil) (incf ip 2))
            (#.+op-app+ (let ((args (vm-pop m)) (func (vm-pop m)))
                          (cond ((= (handle-tag func) +tag-pair+)
                                 (let ((caddr (heap-car heap (handle-index func)))
                                       (cenv  (heap-cdr heap (handle-index func))))
                                   (push-dump-frame m e (+ code-start ip 1))
                                   (setf e cenv)
                                   (unroll-args m args)
                                   (setf ip (fixnum-value caddr))))
                                ((= (handle-tag func) +tag-fixnum+)
                                 (let ((id (logand (fixnum-value func) #xFF)))
                                   (pushv (dispatch-prim m id args)))
                                 (incf ip 1))
                                (t (fail +err-type-error+)))))
            (#.+op-call+ (let ((target (u16-at 1)) (args (vm-pop m)))
                           (push-dump-frame m e (+ code-start ip 3))
                           (unroll-args m args)
                           (setf ip target)))
            (#.+op-rtn+ (let ((frame (pop dump)))
                          (setf e (car frame) ip (cdr frame))))
            (#.+op-prim+ (let ((id (rd-u8 code (off 1))) (args (vm-pop m)))
                           (pushv (dispatch-prim m id args))
                           (incf ip 2)))
            (#.+op-prn+ (let ((v (vm-pop m)))
                          (emit-out m (format-value v))
                          (emit-out m (format nil "~%"))
                          (pushv v)
                          (incf ip 1)))
            (#.+op-gc+ (let ((freed (collect-garbage m))) (pushv (mk-fixnum freed))) (incf ip 1))
            (#.+op-dump+ (emit-event m :dump (list :sp sp :steps (machine-steps m))) (incf ip 1))
            (#.+op-error+ (fail +err-invalid-handle+))
            (t (fail +err-invalid-handle+))))))))

(defun format-value (v)
  (cond ((= (handle-tag v) +tag-fixnum+) (format nil "~D" (fixnum-value v)))
        ((= v +nil+) "nil")
        ((= v +true+) "t")
        ((= v +false+) "nil")
        ((= (handle-tag v) +tag-bytevec+)
         "<bytes>")
        (t "<object>")))

(defun unroll-args (m args)
  (loop while (= (handle-tag args) +tag-pair+)
        do (vm-push m (heap-car (machine-heap m) (handle-index args)))
           (setf args (heap-cdr (machine-heap m) (handle-index args)))))

(defun bin-le (m)
  (let ((b (vm-pop m)) (a (vm-pop m)))
    (vm-push m (mk-bool (<= (fixnum-value a) (fixnum-value b))))))
(defun bin-ge (m)
  (let ((b (vm-pop m)) (a (vm-pop m)))
    (vm-push m (mk-bool (>= (fixnum-value a) (fixnum-value b))))))

(defun collect-garbage (m)
  (let ((roots (append (coerce-to-list-slice m)
                       (list (machine-e m) (machine-g m)))))
    (dolist (fr (machine-dump m))
      (push (car fr) roots)
      (push (mk-fixnum (cdr fr)) roots))
    (heap-gc (machine-heap m) roots)))

(defun coerce-to-list-slice (m)
  (loop for i from 0 below (machine-sp m)
        collect (aref (machine-stack m) i)))

(defun dispatch-prim (m id args)
  (if (boundp '*registry*)
      (let ((fn (gethash id *registry*)))
        (if fn (funcall fn (machine-heap m) args)
            (progn (setf (machine-error-code m) +err-prim-not-found+) +nil+)))
      (progn (setf (machine-error-code m) +err-prim-not-found+) +nil+)))

(defvar *core-op-fns* (make-hash-table)
  "opcode -> fn(heap args-list) => handle; populated by primitives.lisp.")

(defun call-core-op (op heap args)
  (let ((fn (gethash op *core-op-fns*)))
    (if fn (funcall fn heap args)
        (progn (when *current-machine*
                 (setf (machine-error-code *current-machine*) +err-type-error+))
               +nil+))))
(defvar *current-machine* nil)

;;; Public drivers ----------------------------------------------------------
(defun step-once (m)
  (when (and (machine-running m) (zerop (machine-error-code m)))
    (incf (machine-steps m))
    (exec-one m))
  (values (zerop (machine-error-code m)) (machine-error-code m)))

(defun halted-p (m)
  (or (not (machine-running m)) (/= (machine-error-code m) 0)))
