;;;; primitives.lisp — primitive implementations + per-device registry
;;;; (specification §7)
(in-package #:secd-emulator.vm)

(defvar *device-table* (make-hash-table :test 'equal)
  "primitive NAME -> metadata spec hash {id args} for the selected device")

(defvar *prim-impls* (make-hash-table :test 'equal)
  "primitive NAME string -> fn(heap args) => handle")

(defmacro define-prim (name (heap args) &body body)
  `(setf (gethash ,name *prim-impls*)
         (lambda (,heap ,args) ,@body)))

;;; ---- args-list helpers ---------------------------------------------------
(defun arg1 (heap args)
  (if (= (handle-tag args) +tag-pair+) (heap-car heap (handle-index args)) +nil+))

(defun arg2 (heap args)
  (let ((r (if (= (handle-tag args) +tag-pair+) (heap-cdr heap (handle-index args)) +nil+)))
    (if (= (handle-tag r) +tag-pair+) (heap-car heap (handle-index r)) +nil+)))

;;; ---- core list/arithmetic ops -------------------------------------------
(defun p-car (h a)
  (let ((p (arg1 h a)))
    (if (= (handle-tag p) +tag-pair+) (heap-car h (handle-index p)) +nil+)))

(defun p-cdr (h a)
  (let ((p (arg1 h a)))
    (if (= (handle-tag p) +tag-pair+) (heap-cdr h (handle-index p)) +nil+)))

(defun p-cons (h a) (cons-values h (arg1 h a) (arg2 h a)))

(defun p-list (h a)
  (let ((items '()))
    (list-iter h a (lambda (v) (push v items)))
    (list-values h (nreverse items))))

(defun p-add (h a) (mk-fixnum (+ (fixnum-value (arg1 h a)) (fixnum-value (arg2 h a)))))
(defun p-sub (h a) (mk-fixnum (- (fixnum-value (arg1 h a)) (fixnum-value (arg2 h a)))))
(defun p-mul (h a) (mk-fixnum (* (fixnum-value (arg1 h a)) (fixnum-value (arg2 h a)))))
(defun p-div (h a)
  (let ((b (fixnum-value (arg2 h a))))
    (if (zerop b) +nil+
        (mk-fixnum (truncate (fixnum-value (arg1 h a)) b)))))
(defun p-mod (h a)
  (let ((b (fixnum-value (arg2 h a))))
    (if (zerop b) +nil+
        (mk-fixnum (mod (fixnum-value (arg1 h a)) b)))))
(defun p-eq (h a) (mk-bool (= (arg1 h a) (arg2 h a))))
(defun p-lt (h a) (mk-bool (< (fixnum-value (arg1 h a)) (fixnum-value (arg2 h a)))))
(defun p-gt (h a) (mk-bool (> (fixnum-value (arg1 h a)) (fixnum-value (arg2 h a)))))
(defun p-null? (h a) (mk-bool (= (arg1 h a) +nil+)))
(defun p-pair? (h a) (mk-bool (= (handle-tag (arg1 h a)) +tag-pair+)))
(defun p-atom? (h a)
  (let ((v (arg1 h a)))
    (mk-bool (and (/= (handle-tag v) +tag-pair+) (/= v +nil+)))))

(defun machine-real-ms ()
  (floor (* 1000 (get-internal-real-time)) internal-time-units-per-second))

;;; ---- UTF-16 encoder ------------------------------------------------------
(defun utf8-codepoints (bytes)
  (let ((cps '()) (i 0) (n (length bytes)))
    (loop while (< i n)
          do (let ((b0 (aref bytes i)))
               (cond
                 ((< b0 #x80) (push b0 cps) (incf i))
                 ((< b0 #xE0) (when (<= (+ i 2) n)
                                (push (logior (ash (logand b0 #x1F) 6)
                                              (logand (aref bytes (+ i 1)) #x3F))
                                      cps))
                              (incf i 2))
                 ((< b0 #xF0) (when (<= (+ i 3) n)
                                (push (logior (ash (logand b0 #x0F) 12)
                                              (ash (logand (aref bytes (+ i 1)) #x3F) 6)
                                              (logand (aref bytes (+ i 2)) #x3F))
                                      cps))
                              (incf i 3))
                 (t (when (<= (+ i 4) n)
                      (push (logior (ash (logand b0 #x07) 18)
                                    (ash (logand (aref bytes (+ i 1)) #x3F) 12)
                                    (ash (logand (aref bytes (+ i 2)) #x3F) 6)
                                    (logand (aref bytes (+ i 3)) #x3F))
                                      cps))
                    (incf i 4)))))
    (nreverse cps)))

;;; ------------------------- bignum core -----------------------------------

(defun bn-view (h v)
  "BIGNUM handle -> (values magnitude-ub8 sign); NIL when not a BIGNUM."
  (when (= (handle-tag v) +tag-bignum+)
    (let* ((idx (handle-index v))
           (sign (heap-car h idx))
           (slot (logand (heap-cdr h idx) #x0FFF))
           (len (bv-len h slot))
           (buf (make-array len :element-type '(unsigned-byte 8))))
      (dotimes (i len) (setf (aref buf i) (bv-read h slot i)))
      (values buf sign))))

(defun bn-make (h data sign)
  ;; normalize: strip leading zero bytes; canonical zero = single 0x00
  (let* ((end (length data)))
    (loop while (and (> end 0) (zerop (aref data (1- end)))) do (decf end))
    (let* ((mag (if (plusp end) (subseq data 0 end) #(0)))
           (sgn (if (plusp end) sign 0))
           (mslot (bv-alloc h (length mag))))
      (dotimes (i (length mag)) (bv-write h mslot i (aref mag i)))
      (let ((oi (heap-alloc h +tag-bignum+)))
        (set-heap-car h oi sgn)
        (set-heap-cdr h oi mslot)
        (mk-handle +tag-bignum+ oi)))))

(defun bn-of-integer (h value)
  (let* ((neg (< value 0))
         (m (abs value))
         (bytes '()))
    (loop while (plusp m)
          do (push (logand m #xFF) bytes)
             (setf m (ash m -8)))
    (bn-make h (coerce (or bytes (list 0)) '(vector (unsigned-byte 8)))
             (if neg 1 0))))

(defun bn-zero-p (v) (every #'zerop v))

(defun bn-cmp-mag (a b)
  (cond ((< (length a) (length b)) -1)
        ((> (length a) (length b)) 1)
        (t (loop for i from (1- (length a)) downto 0
                 do (cond ((< (aref a i) (aref b i)) (return -1))
                          ((> (aref a i) (aref b i)) (return 1)))
                 finally (return 0)))))

(defun bn-add-mag (a b)
  (let* ((n (max (length a) (length b)))
         (out (make-array n :element-type '(unsigned-byte 8)))
         (carry 0))
    (dotimes (i n)
      (let ((s (+ carry
                  (if (< i (length a)) (aref a i) 0)
                  (if (< i (length b)) (aref b i) 0))))
        (setf (aref out i) (logand s #xFF)
              carry (ash s -8))))
    (if (plusp carry)
        (concatenate '(vector (unsigned-byte 8)) out (vector carry))
        out)))

(defun bn-sub-mag (a b)
  (let* ((out (copy-seq a)) (borrow 0))
    (dotimes (i (length out))
      (let ((s (- (aref out i) borrow
                  (if (< i (length b)) (aref b i) 0))))
        (setf borrow (if (< s 0) 1 0)
              (aref out i) (logand s #xFF))))
    out))

(defun bn-mag-int (v)
  (let ((m 0))
    (loop for i from (1- (length v)) downto 0
          do (setf m (logior (ash m 8) (aref v i))))
    m))

(defun trim-le (arr)
  (let ((end (length arr)))
    (loop while (and (> end 1) (zerop (aref arr (1- end)))) do (decf end))
    (subseq arr 0 end)))

(defun bn-divmod-mag (a b)
  "Binary shift-subtract division of magnitudes: (values quotient remainder)."
  (let* ((bits (* 8 (length a)))
         (qbits (make-array bits :element-type 'bit :initial-element 0))
         (r 0)
         (bint (bn-mag-int b)))
    (dotimes (k bits)
      (let ((bitpos (- bits 1 k)))
        (setf r (logior (ash r 1)
                        (ldb (byte 1 (mod bitpos 8)) (aref a (floor bitpos 8)))))
        (when (>= r bint)
          (decf r bint)
          (setf (bit qbits bitpos) 1))))
    (let ((q (make-array (ceiling bits 8) :element-type '(unsigned-byte 8)
                                          :initial-element 0)))
      (dotimes (k bits)
        (when (= 1 (bit qbits k))
          (incf (aref q (floor k 8)) (ash 1 (mod k 8)))))
      (let ((rb (make-array 4 :element-type '(unsigned-byte 8))))
        (dotimes (i 4) (setf (aref rb i) (ldb (byte 8 (* 8 i)) r)))
        (values (trim-le q) (trim-le rb))))))

(defun divmod-1e9! (work)
  "Divide LE magnitude WORK by 10^9 in place; returns remainder."
  (let* ((total (bn-mag-int work))
         (q (floor total 1000000000))
         (r (mod total 1000000000)))
    (dotimes (i (length work))
      (setf (aref work i) (ldb (byte 8 (* 8 i)) q)))
    r))

;;; ------------------------- bn primitives ----------------------------------

(defun bn-register-all (machine)
  (declare (ignore machine))
  (define-prim "%bn-sub" (h a)
    (multiple-value-bind (da sa) (bn-view h (arg1 h a))
      (multiple-value-bind (db sb) (bn-view h (arg2 h a))
        (if (or (null da) (null db)) +nil+
            (let ((sb2 (- 1 sb)))
              (if (= sa sb2)
                  ;; same effective sign after negation: magnitudes add
                  (bn-make h (bn-add-mag da db) sa)
                  (let ((c (bn-cmp-mag da db)))
                    (cond ((zerop c)
                           (bn-make h (make-array 1 :element-type '(unsigned-byte 8)
                                                      :initial-element 0) 0))
                          ((plusp c) (bn-make h (bn-sub-mag da db) sa))
                          (t         (bn-make h (bn-sub-mag db da) sb2)))))))))))
  (define-prim "%bn-mul" (h a)
    (multiple-value-bind (da sa) (bn-view h (arg1 h a))
      (multiple-value-bind (db sb) (bn-view h (arg2 h a))
        (cond ((or (null da) (null db) (bn-zero-p da) (bn-zero-p db))
               (bn-make h (make-array 1 :element-type '(unsigned-byte 8) :initial-element 0) 0))
              (t
               (let* ((n (+ (length da) (length db)))
                      (acc (make-array n :element-type '(unsigned-byte 8)
                                            :initial-element 0)))
                 (dotimes (i (length da))
                   (let ((carry 0))
                     (dotimes (j (length db))
                       (let ((cur (+ (aref acc (+ i j))
                                     (* (aref da i) (aref db j))
                                     carry)))
                         (setf (aref acc (+ i j)) (logand cur #xFF)
                               carry (ash cur -8))))
                     (let ((k (+ i (length db))))
                       (loop while (plusp carry)
                             do (let ((cur (+ (aref acc k) carry)))
                                  (setf (aref acc k) (logand cur #xFF)
                                        carry (ash cur -8)))
                                (incf k)))))
                 (bn-make h acc (logxor sa sb))))))))
  (define-prim "%bn-div" (h a)
    (multiple-value-bind (da sa) (bn-view h (arg1 h a))
      (multiple-value-bind (db sb) (bn-view h (arg2 h a))
        (cond ((or (null da) (null db) (bn-zero-p db)) +nil+)
              ((< (bn-cmp-mag da db) 0)
               (bn-make h (make-array 1 :element-type '(unsigned-byte 8) :initial-element 0) 0))
              (t (multiple-value-bind (q r) (bn-divmod-mag da db)
                   (declare (ignore r))
                   (bn-make h q (logxor sa sb))))))))
  (define-prim "%bn-mod" (h a)
    (multiple-value-bind (da sa) (bn-view h (arg1 h a))
      (multiple-value-bind (db sb) (bn-view h (arg2 h a))
        (declare (ignore sb))
        (cond ((or (null da) (null db) (bn-zero-p db)) +nil+)
              ((< (bn-cmp-mag da db) 0) (bn-make h da sa))
              (t (multiple-value-bind (q r) (bn-divmod-mag da db)
                   (declare (ignore q))
                   (bn-make h r sa)))))))
  (define-prim "%bn-cmp" (h a)
    (multiple-value-bind (da sa) (bn-view h (arg1 h a))
      (multiple-value-bind (db sb) (bn-view h (arg2 h a))
        (declare (ignore sb))
        (cond ((or (null da) (null db)) +nil+)
              ((and (bn-zero-p da) (bn-zero-p db)) (mk-fixnum 0))
              ((bn-zero-p da) (mk-fixnum (if (= sa 1) -1 1)))
              ((bn-zero-p db) (mk-fixnum (if (= sa 1) 1 -1)))
              (t (let ((c (bn-cmp-mag da db)))
                   (mk-fixnum (if (= sa 1) (- c) c))))))))
  (define-prim "%bn-to-string" (h a)
    (multiple-value-bind (da sa) (bn-view h (arg1 h a))
      (if (null da) +nil+
          (let* ((neg (= sa 1))
                 (work (copy-seq da))
                 (chunks '()))
            (loop while (not (bn-zero-p work))
                  do (push (divmod-1e9! work) chunks))
            (when (null chunks) (push 0 chunks))
            (let* ((str (with-output-to-string (out)
                          (when neg (write-char #\- out))
                          (format out "~D" (first chunks))
                          (dolist (c (rest chunks))
                            (format out "~9,'0D" c))))
                   (bytes (map '(vector (unsigned-byte 8)) #'char-code str))
                   (slot (bv-alloc h (length bytes))))
              (dotimes (k (length bytes))
                (bv-write h slot k (aref bytes k)))
              (mk-handle +tag-bytevec+ slot))))))
  (define-prim "%bn-from-string" (h a)
    (let* ((sv (arg1 h a))
           (slot (and (= (handle-tag sv) +tag-bytevec+) (handle-index sv))))
      (if (null slot) +nil+
          (let* ((len (bv-len h slot))
                 (acc 0) (sign 1) (seen nil) (ok t))
            (loop for i below len
                  for ch = (code-char (bv-read h slot i))
                  do (cond ((and (= i 0) (char= ch #\-)) (setf sign -1))
                           ((digit-char-p ch)
                            (setf acc (+ (* acc 10) (- (char-code ch) 48)) seen t))
                           (t (setf ok nil))))
            (if (and ok seen)
                (bn-of-integer h (* sign acc))
                +nil+)))))

;;; ---- registry --------------------------------------------------------------

(defvar *registry* nil)

(defun register-device-prims (machine)
  (let ((reg (make-hash-table)))
    (maphash
     (lambda (name spec)
       (let ((id (gethash "id" spec))
             (fn (gethash name *prim-impls*)))
         (when (and id fn)
           (setf (gethash id reg) fn))))
     *device-table*)
    (labels ((by (nm) (lambda (h a) (funcall (gethash nm *prim-impls*) h a))))
      (setf (gethash +op-add+ *core-op-fns*) (by "+"))
      (setf (gethash +op-sub+ *core-op-fns*) (by "-"))
      (setf (gethash +op-mul+ *core-op-fns*) (by "*"))
      (setf (gethash +op-div+ *core-op-fns*) (by "/"))
      (setf (gethash +op-mod+ *core-op-fns*) (by "%"))
      (setf (gethash +op-eq+  *core-op-fns*) (by "="))
      (setf (gethash +op-lt+  *core-op-fns*) (by "<"))
      (setf (gethash +op-gt+  *core-op-fns*) (by ">")))
    (setf *registry* reg)))

;;; ---- default install --------------------------------------------------------

(defun install-hal-sims (machine)
  (define-prim "%gpio-init" (h a)
    (declare (ignore h))
    (emit-event machine :gpio-init (list :pin (fixnum-value (arg1 h a))
                                         :mode (fixnum-value (arg2 h a))))
    (mk-fixnum 0))
  (define-prim "%gpio-write" (h a)
    (declare (ignore h))
    (let ((pin (fixnum-value (arg1 h a))) (val (fixnum-value (arg2 h a))))
      (emit-event machine :gpio-write (list :pin pin :value val))
      (mk-fixnum 0)))
  (define-prim "%gpio-read" (h a)
    (declare (ignore h))
    (mk-fixnum 0))
  (define-prim "%uart-init" (h a)
    (emit-event machine :uart-init (list :baud (as-int (arg1 h a))))
    +nil+)
  (define-prim "%uart-write" (h a)
    (emit-out machine (string (code-char (fixnum-value (arg1 h a)))))
    +nil+)
  (define-prim "%uart-read" (h a)
    (declare (ignore h a))
    (let ((q (machine-console-in machine)))
      (if (plusp (fill-pointer q))
          (prog1 (mk-fixnum (aref q 0))
            (replace q q :start1 0 :start2 1)
            (decf (fill-pointer q)))
          (mk-fixnum 0))))
  (define-prim "%serial-avail" (h a)
    (declare (ignore h a))
    (mk-fixnum (if (plusp (fill-pointer (machine-console-in machine))) 1 0)))
  (define-prim "%i2c-init" (h a)
    (emit-event machine :i2c-init (list :sda (fixnum-value (arg1 h a))
                                        :scl (fixnum-value (arg2 h a))
                                        :khz (as-int (arg3 h a))))
    (mk-fixnum 0))
  (define-prim "%adc-read" (h a) (declare (ignore h a)) (mk-fixnum 0))
  (define-prim "%pwm-write" (h a) (declare (ignore h a)) (mk-fixnum 0))
  (define-prim "%wave-play" (h a) (declare (ignore h a)) +nil+))

(defun as-int (v)
  "Decode FIXNUM or BIGNUM argument to an integer."
  (if (= (handle-tag v) +tag-bignum+)
      (multiple-value-bind (data sign) (bn-view (machine-heap *current-machine*) v)
        (if (null data) 0
            (let ((m (bn-mag-int data)))
              (if (= sign 1) (- m) m))))
      (fixnum-value v)))

(defun install-default-prims (machine)
  (define-prim "car" (h a) (p-car h a))
  (define-prim "cdr" (h a) (p-cdr h a))
  (define-prim "cons" (h a) (p-cons h a))
  (define-prim "list" (h a) (p-list h a))
  (define-prim "+" (h a) (p-add h a))
  (define-prim "-" (h a) (p-sub h a))
  (define-prim "*" (h a) (p-mul h a))
  (define-prim "/" (h a) (p-div h a))
  (define-prim "%" (h a) (p-mod h a))
  (define-prim "=" (h a) (p-eq h a))
  (define-prim "<" (h a) (p-lt h a))
  (define-prim ">" (h a) (p-gt h a))
  (define-prim "null?" (h a) (p-null? h a))
  (define-prim "pair?" (h a) (p-pair? h a))
  (define-prim "atom?" (h a) (p-atom? h a))
  (define-prim "%sleep" (h a)
    (declare (ignore h))
    (sleep (/ (min (as-int (arg1 h a)) 500) 1000.0))
    +nil+)
  (define-prim "%millis" (h a)
    (declare (ignore h a))
    (mk-fixnum (mod (truncate (machine-real-ms)) 2048)))
  (define-prim "utf16-enc" (h a)
    (let* ((sv (arg1 h a))
           (slot (and (= (handle-tag sv) +tag-bytevec+) (handle-index sv)))
           (n (if slot (bv-len h slot) 0))
           (buf (make-array n :element-type '(unsigned-byte 8))))
      (dotimes (i n) (setf (aref buf i) (bv-read h slot i)))
      (let* ((cps (utf8-codepoints buf))
             (units '()))
        (dolist (cp cps)
          (if (>= cp #x10000)
              (let* ((v (- cp #x10000))
                     (hi (logior #xD800 (ash v -10)))
                     (lo (logior #xDC00 (logand v #x3FF))))
                (push (logand lo #xFF) units) (push (ash lo -8) units)
                (push (logand hi #xFF) units) (push (ash hi -8) units))
              (progn (push (logand cp #xFF) units)
                     (push (ash cp -8) units))))
        (let* ((out (coerce (nreverse units) '(vector (unsigned-byte 8))))
               (oslot (bv-alloc h (length out))))
          (dotimes (k (length out)) (bv-write h oslot k (aref out k)))
          (mk-handle +tag-bytevec+ oslot)))))
  (bn-register-all machine)
  (install-hal-sims machine))
