(load "~/quicklisp/setup.lisp")
(ql:quickload '(:clack :clack-handler-wookie :websocket-driver :com.inuoe.jzon :bordeaux-threads :cl-base64 :babel :flexi-streams :alexandria) :verbose nil)
;; Ensure fresh packages (defpackage :use :cl is not updated on redefinition)
(ignore-errors (when (find-package :secd-emulator.web) (delete-package :secd-emulator.web)))
(ignore-errors (when (find-package :secd-emulator.vm) (delete-package :secd-emulator.vm)))
(load "src/vm/package.lisp")
(load "src/vm/values.lisp")
(load "src/vm/machine.lisp")
(load "src/vm/primitives.lisp")
(load "src/web/package.lisp")
(load "src/web/generated-assets.lisp")
(load "src/web/server.lisp")
(format t "starting dev server via dev.lisp...~%")
(secd-emulator.web:start-server :address "0.0.0.0" :port 8899)
