#!/usr/bin/env python3
"""Generate src/web/generated-assets.lisp from www/ files and
secd-machine/targets/. Called by Makefile before every build."""
import json, glob, base64, os

repo = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
www = os.path.join(repo, "www")
targets = os.path.normpath(os.path.join(repo, "..", "secd-machine", "targets"))
out_path = os.path.join(repo, "src", "web", "generated-assets.lisp")

def b64(path):
    return base64.b64encode(open(path, "rb").read()).decode()

# --- static assets ---
index_html = b64(os.path.join(www, "index.html"))
js_path = os.path.join(www, "js", "main.js")
if os.path.exists(js_path):
    js_main = b64(js_path)
else:
    js_main = base64.b64encode(b"/* not built */").decode()

# --- precompiled .secd examples ---
bytecodes = []
for f in sorted(glob.glob(os.path.join(www, "*.secd"))):
    bytecodes.append((os.path.basename(f), b64(f)))

# --- device catalog: merge chips under boards ---
chips = {}
chip_dir = os.path.join(targets, "chips")
if os.path.isdir(chip_dir):
    for f in sorted(glob.glob(os.path.join(chip_dir, "*.json"))):
        d = json.loads(open(f).read())
        chips[d["chip"]] = d

boards = []
board_dir = os.path.join(targets, "boards")
if os.path.isdir(board_dir):
    for f in sorted(glob.glob(os.path.join(board_dir, "*.json"))):
        b = json.loads(open(f).read())
        base = chips.get(b.get("chip"))
        if base:
            merged = dict(base)
            merged.update(b)
            boards.append(merged)

catalog_b64 = base64.b64encode(json.dumps(boards).encode()).decode()

# --- generate Lisp ---
L = []
L.append(';;;; generated-assets.lisp — AUTO-GENERATED by tools/gen-assets.py')
L.append(';;;; Do not edit; changes will be overwritten on next build.')
L.append('(in-package #:secd-emulator.web)')
L.append('')
L.append(f'(defparameter *asset-index-html*')
L.append(f'  (babel:octets-to-string (cl-base64:base64-string-to-usb8-array "{index_html}")))')
L.append('')
L.append(f'(defparameter *asset-js-main*')
L.append(f'  (babel:octets-to-string (cl-base64:base64-string-to-usb8-array "{js_main}")))')
L.append('')
L.append(f'(defparameter *device-catalog-json*')
L.append(f'  (babel:octets-to-string (cl-base64:base64-string-to-usb8-array "{catalog_b64}")))')
L.append('')
if bytecodes:
    L.append('(defparameter *embedded-bytecodes*')
    L.append('  (list')
    for name, data in bytecodes:
        L.append(f'    (cons "{name}"')
        L.append(f'         (cl-base64:base64-string-to-usb8-array "{data}"))')
    L.append('))')
else:
    L.append('(defparameter *embedded-bytecodes* nil)')

os.makedirs(os.path.dirname(out_path), exist_ok=True)
with open(out_path, "w") as f:
    f.write("\n".join(L) + "\n")

print(f"generated {out_path}: catalog={len(boards)} boards, bytecodes={len(bytecodes)}")
